# -*- coding: utf-8 -*-
"""CienciaDeDatos_MedidasCentrales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRFv-98m7EbS2_DQ7XcyA3KFXejSbWm4
"""

!pip install statsmodels
!pip install wquantiles

import pandas as pd
import numpy as np
from scipy.stats import trim_mean
from statsmodels import robust
import wquantiles
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/state.csv')
df

df.info()

df.describe()

promedio_poblacion = df['Population'].mean()
print("El promedio de la población es: ", promedio_poblacion)

promedio_poblacion_trim = trim_mean(df['Population'], 0.1)
print("El promedio Trimeado es: ", promedio_poblacion_trim)

media_ponderada = np.average(df['Murder.Rate'], weights=df['Population'])
print("La media ponderada es: ", media_ponderada)

df['Murder.Rate'].plot.line()

sns.barplot(x=df.index, y=df['Murder.Rate'], palette='cubehelix')

sns.histplot(df.Population / 1_000_000, palette="Pastel1")
plt.xlabel("Población [Millones]")
plt.show()

ax = df["Murder.Rate"].plot.hist(figsize=(8, 6), bins=20, color='skyblue', edgecolor='black')
ax.set_xlabel("Murder Rate")
plt.tight_layout()
plt.show()

analisis = df.head(10)
g = sns.FacetGrid(analisis, col = 'State')
g.map(sns.distplot, 'Murder.Rate')

