# -*- coding: utf-8 -*-
"""Ciencia_De_Datos_Medidas_Centrales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMfO4-yBGu8vSTLt3D27mUqbq-yI4yOv
"""

!pip install statsmodels
!pip install wquantiles

import kagglehub
import os

path = kagglehub.dataset_download("yasserh/wine-quality-dataset")

print("Path to dataset files:", path)

directory_path = '/root/.cache/kagglehub/datasets/yasserh/wine-quality-dataset/versions/1'
files = os.listdir(directory_path)
print(files)

import pandas as pd
import numpy as np
from scipy.stats import trim_mean
from statsmodels import robust
import wquantiles
import seaborn as sns
import matplotlib.pyplot as plt

file_path = '/root/.cache/kagglehub/datasets/yasserh/wine-quality-dataset/versions/1/WineQT.csv'

df = pd.read_csv(file_path)
df

df.info()

df.describe()

promedio_acidez = df['fixed acidity'].mean()
print("El promedio de la acidez es: ", promedio_acidez)

promedio_acidez_trim = trim_mean(df['fixed acidity'], 0.1)
print("El promedio Trimeado es: ", promedio_acidez_trim)

media_ponderada = np.average(df['alcohol'], weights=df['fixed acidity'])
print("La media ponderada es: ", media_ponderada)

df['alcohol'].plot.line()

sns.barplot(x = df.index, y = df['alcohol'], palette='coolwarm')

sns.histplot(df["fixed acidity"], kde=False, color='skyblue', bins=20)
plt.xlabel("Acidez")
plt.show()

ax = df["alcohol"].plot.hist(figsize=(8, 6), bins=20, color='skyblue', edgecolor='black')
ax.set_xlabel("Alcohol")
plt.tight_layout()
plt.show()

analisis = df.head(10)
g = sns.FacetGrid(analisis, col = "fixed acidity")
g.map(sns.distplot, "alcohol")

# Calcular la correlación entre 'fixed acidity' y 'alcohol'
correlation = df['fixed acidity'].corr(df['alcohol'])
print("La correlación entre acidez fija y alcohol es:", correlation)

# Gráfico de dispersión para visualizar la relación entre acidez y alcohol
sns.scatterplot(x = 'fixed acidity', y = 'alcohol', data = df)
plt.title("Relación entre acidez y alcohol en el vino")
plt.xlabel("Acidez fija")
plt.ylabel("Alcohol")
plt.show()

# Calcular la mediana ponderada del alcohol utilizando 'fixed acidity' como pesos
weighted_median_alcohol = wquantiles.median(df['alcohol'], weights = df['fixed acidity'])
print("La mediana ponderada del alcohol es:", weighted_median_alcohol)

# Calcular la desviación absoluta mediana (MAD) de la acidez (una medida robusta de dispersión)
mad_acidity = robust.mad(df['fixed acidity'])
print("La desviación absoluta mediana (MAD) de la acidez es:", mad_acidity)

# Histograma y densidad de probabilidad para 'fixed acidity' y 'alcohol'
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.histplot(df['fixed acidity'], kde=True, bins=30)
plt.title("Distribución de la acidez fija")
plt.xlabel("Acidez fija")

plt.subplot(1, 2, 2)
sns.histplot(df['alcohol'], kde=True, bins=30)
plt.title("Distribución del alcohol")
plt.xlabel("Alcohol")

plt.tight_layout()
plt.show()

# Estadísticas descriptivas para 'fixed acidity' y 'alcohol'
desc_stats = df[['fixed acidity', 'alcohol']].describe()
print("Estadísticas descriptivas para acidez y alcohol:\n", desc_stats)

# Regresión lineal simple: predecir el alcohol en función de la acidez fija
import statsmodels.api as sm

X = df['fixed acidity']
y = df['alcohol']
X = sm.add_constant(X)  # Añadimos la constante (intercepto)

modelo = sm.OLS(y, X).fit()
print(modelo.summary())

"""Con base en los resultados de la regresión lineal, podemos extraer las siguientes conclusiones principales:

**Relación lineal muy débil**

El valor de R^2 es aproximadamente 0.006 (0.6%), lo que indica que la acidez fija explica muy poca variabilidad en el contenido de alcohol.

En términos prácticos, esto significa que hay muchos otros factores dentro del dataset que influyen en el nivel de alcohol del vino.

**Pendiente negativa y significativa**

El coeficiente de la acidez fija es de alrededor de -0.0465 con un p-value de 0.011, por debajo del umbral típico de 0.05.

La significancia estadística indica que el efecto no es producto del azar, pero el efecto es pequeño: por cada aumento de 1 unidad en la acidez, el alcohol se reduce en tan solo 0.0465 unidades.

**Interpretación**

Aunque el coeficiente sea estadísticamente significativo, el tamaño del efecto (y la capacidad de predicción) es muy bajo.

En la práctica, la acidez fija no es un buen predictor del contenido de alcohol, por lo que sería necesario incluir otras variables (como el tipo de uva, la región, el proceso de fermentación, etc.) para explicar mejor el nivel de alcohol en el vino.

**Conclusión**

A partir del análisis que realizamos, se puede decir que existe una relación negativa leve entre la acidez y el alcohol, pero es tan pequeña que no resulta útil para predecir el alcohol de un vino basándonos solo en la acidez.
"""